# Generated by Django 4.2 on 2023-04-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0003_location_alter_meetup_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="test@test.ca", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="participant",
            field=models.ManyToManyField(
                blank=True, null=True, to="meetups.participant"
            ),
        ),
    ]
