# Generated by Django 4.2 on 2023-04-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0005_remove_meetup_date_remove_meetup_organizer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="bart@test.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="participant",
            field=models.ManyToManyField(
                blank=True, null=True, to="meetups.participant"
            ),
        ),
    ]
